UNAME := $(shell uname)
ifeq ($(UNAME), Linux)
	RUN_ := .\main.o
else
	RUN_ := .\main.exe
endif

run:
	g++ .\main.cpp -o .\main -pass-exit-codes && $(RUN_)
	
time:
	g++ .\main.cpp -o .\main -ftime-report && $(RUN_)
	
	